language: php

php:
  - 7
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

env:
  - LARAVEL_VERSION="~5.2" TESTBENCH_VERSION="~3.2"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script: phpunit

sudo: false

notifications:
  slack: asgardcms:rQqM7V2EoZOrsv6GgAemZyOS
  email:
    - n.widart@gmail.com
    - josh@joshbrown.me
