language: php

php:
  - 7
  - 5.6

env:
  - LARAVEL_VERSION="~5.2" TESTBENCH_VERSION="~3.2"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

sudo: false

notifications:
  email:
    - n.widart@gmail.com
    - josh@joshbrown.me
